version: "3.8"

services:
  postgres:
    image: postgres:latest
    hostname: accounting-postgres
    container_name: accounting-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ITegH6d64TBSzs9faJ5Z
    ports:
      - "5432:5432"
    volumes:
      - accounting_postgres_data:/var/lib/postgresql/data

volumes:
  accounting_postgres_data:
